# Setup
title:               mu88
tagline:             'Developer Blog'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://github.com/mu88/mu88.github.io
baseurl:             'https://mu88.github.io'
paginate:            5
stackoverflow:       https://stackoverflow.com/users/4919526/mu88

# GitHub
github:
  repo:              https://github.com/mu88/mu88.github.io

# About/contact
author:
  name:              mu88
  url:               https://stackoverflow.com/users/4919526/mu88
  email:             mu88_developer@outlook.com

# Custom vars
version:             1.0.0
