# Setup
title:               mu88
tagline:             'Developer Blog'
description:         'Just another blog of just another software developer out there. Thanks to <a href="https://twitter.com/mdo" target="_blank">@mdo</a> for providing the amazing Jekyll theme!'
url:                 https://github.com/mu88/mu88.github.io
baseurl:             'https://mu88.github.io'
paginate:            5

# GitHub
github:
  repo:              https://github.com/mu88/mu88.github.io

# About/contact
author:
  name:              mu88
  url:               https://stackoverflow.com/users/4919526/mu88
  email:             mu88_developer@outlook.com
  stackoverflow:     https://stackoverflow.com/users/4919526/mu88
  github:            https://github.com/mu88

# Custom vars
version:             1.0.0

plugins:
  - jekyll-seo-tag